#:schema node_modules/wrangler/config-schema.json
name = "links"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = [
    "nodejs_compat",
]

# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
[placement]
mode = "smart"

# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "KV"
id      = "4661ca77136847b3a3069b30734c2e01"

# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/routes
[[routes]]
pattern       = "link.toryn.bio"
custom_domain = true
zone_id       = "6d83bd758e025e6d0ee51302a450b0d1"

[[routes]]
pattern       = "xn--qv8h.toryn.bio"
custom_domain = true
zone_id       = "6d83bd758e025e6d0ee51302a450b0d1"
